name: tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test-rust:
    name: Test Rust main library
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2

    - name: Run tests
      run: cargo test --project openlineage_sql

  test-python:
    name: Test Python interface
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.7"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --dev

    - name: Run linters
      run: uv run ruff check

    - name: Run tests
      run: uv run pytest